version: '2'

services:
  idrac1:
    image: domistyle/idrac6
    build:
      context: ./
    restart: always
    volumes:
      - ./app:/app
    ports:
      - 5800:5800
      - 5900:5900
    environment:
      - IDRAC_HOST=192.168.0.1
      - IDRAC_USER=root
      - IDRAC_PASSWORD=calvin
