version: '2'

services:
  idrac1:
    image: domistyle/idrac6
    restart: always
    ports:
      - 5800:5800
      - 5900:5900
    environment:
      - IDRAC_HOST=idrac1.example.org
      - IDRAC_USER=root
      - IDRAC_PASSWORD=1234
    volumes:
      - /path/to/app:/app
      - /path/to/media:/vmedia
      - /path/to/screenshots:/screenshots
  idrac2:
    image: domistyle/idrac6
    restart: always
    ports:
      - 5801:5800
      - 5901:5900
    environment:
      - IDRAC_HOST=idrac2.example.org
      - IDRAC_USER=root
      - IDRAC_PASSWORD=1234
    volumes:
      - /path/to/app:/app
      - /path/to/media:/vmedia
      - /path/to/screenshots:/screenshots
